### ISSUE TITLE
GoogleAIStudio not connect  API

### ISSUE THREAD

**Issue by l33tm3** [ragapp/ragapp#11]
**Describe the bug**
Google AI Studio not connect  

**To Reproduce**
1. Set API Key on RagAPP
2. Select model Gemini 1.5 Pro

**LOG**
024-05-24 15:12:44 INFO:     Connecting vector store...
2024-05-24 15:12:44 INFO:app.engine.vectordb:Using vector provider: chroma
2024-05-24 15:12:44 INFO:chromadb.api.segment:Collection default is not created.
2024-05-24 15:12:44 INFO:     Finished load index from vector store.
2024-05-24 15:12:45 INFO:     172.17.0.1:54796 - "POST /api/chat HTTP/1.1" 500 Internal Server Error
2024-05-24 15:12:45 ERROR:    Exception in ASGI application
2024-05-24 15:12:45 Traceback (most recent call last):
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/callbacks/base.py", line 178, in event
2024-05-24 15:12:45     yield event
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 719, in astream_chat
2024-05-24 15:12:45     chat_response = await self._achat(
2024-05-24 15:12:45                     ^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in async_wrapper
2024-05-24 15:12:45     result = await func(*args, **kwargs)
2024-05-24 15:12:45              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 611, in _achat
2024-05-24 15:12:45     cur_step_output = await self._arun_step(
2024-05-24 15:12:45                       ^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in async_wrapper
2024-05-24 15:12:45     result = await func(*args, **kwargs)
2024-05-24 15:12:45              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 454, in _arun_step
2024-05-24 15:12:45     cur_step_output = await self.agent_worker.astream_step(step, task, **kwargs)
2024-05-24 15:12:45                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/callbacks/utils.py", line 56, in async_wrapper
2024-05-24 15:12:45     return await func(self, *args, **kwargs)
2024-05-24 15:12:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/agent/react/step.py", line 758, in astream_step
2024-05-24 15:12:45     return await self._arun_step_stream(step, task)
2024-05-24 15:12:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/agent/react/step.py", line 687, in _arun_step_stream
2024-05-24 15:12:45     async for latest_chunk in chat_stream:
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 78, in wrapped_gen
2024-05-24 15:12:45     async for x in f_return_val:
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/llms/custom.py", line 58, in gen
2024-05-24 15:12:45     for message in self.stream_chat(messages, **kwargs):
2024-05-24 15:12:45                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/llms/gemini/base.py", line 196, in stream_chat
2024-05-24 15:12:45     response = chat.send_message(next_msg, stream=True)
2024-05-24 15:12:45                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/google/generativeai/generative_models.py", line 496, in send_message
2024-05-24 15:12:45     response = self.model.generate_content(
2024-05-24 15:12:45                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/google/generativeai/generative_models.py", line 256, in generate_content
2024-05-24 15:12:45     iterator = self._client.stream_generate_content(
2024-05-24 15:12:45                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 1107, in stream_generate_content
2024-05-24 15:12:45     response = rpc(
2024-05-24 15:12:45                ^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
2024-05-24 15:12:45     return wrapped_func(*args, **kwargs)
2024-05-24 15:12:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
2024-05-24 15:12:45     return retry_target(
2024-05-24 15:12:45            ^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
2024-05-24 15:12:45     _retry_error_helper(
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
2024-05-24 15:12:45     raise final_exc from source_exc
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
2024-05-24 15:12:45     result = target()
2024-05-24 15:12:45              ^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
2024-05-24 15:12:45     return func(*args, **kwargs)
2024-05-24 15:12:45            ^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 174, in error_remapped_callable
2024-05-24 15:12:45     raise exceptions.from_grpc_error(exc) from exc
2024-05-24 15:12:45 google.api_core.exceptions.InvalidArgument: 400 Add an image to use models/gemini-pro-vision, or switch your model to a text model.
2024-05-24 15:12:45 
2024-05-24 15:12:45 During handling of the above exception, another exception occurred:
2024-05-24 15:12:45 
2024-05-24 15:12:45 Traceback (most recent call last):
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2024-05-24 15:12:45     result = await app(  # type: ignore[func-returns-value]
2024-05-24 15:12:45              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-05-24 15:12:45     return await self.app(scope, receive, send)
2024-05-24 15:12:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-05-24 15:12:45     await super().__call__(scope, receive, send)
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-05-24 15:12:45     await self.middleware_stack(scope, receive, send)
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-05-24 15:12:45     raise exc
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-05-24 15:12:45     await self.app(scope, receive, _send)
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-05-24 15:12:45     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-24 15:12:45     raise exc
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-24 15:12:45     await app(scope, receive, sender)
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-05-24 15:12:45     await self.middleware_stack(scope, receive, send)
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-05-24 15:12:45     await route.handle(scope, receive, send)
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-05-24 15:12:45     await self.app(scope, receive, send)
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-05-24 15:12:45     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-24 15:12:45     raise exc
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-24 15:12:45     await app(scope, receive, sender)
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-05-24 15:12:45     response = await func(request)
2024-05-24 15:12:45                ^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-05-24 15:12:45     raw_response = await run_endpoint_function(
2024-05-24 15:12:45                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-05-24 15:12:45     return await dependant.call(**values)
2024-05-24 15:12:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/app/create_llama/backend/app/api/routers/chat.py", line 96, in chat
2024-05-24 15:12:45     response = await chat_engine.astream_chat(last_message_content, messages)
2024-05-24 15:12:45                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in async_wrapper
2024-05-24 15:12:45     result = await func(*args, **kwargs)
2024-05-24 15:12:45              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/callbacks/utils.py", line 56, in async_wrapper
2024-05-24 15:12:45     return await func(self, *args, **kwargs)
2024-05-24 15:12:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 715, in astream_chat
2024-05-24 15:12:45     with self.callback_manager.event(
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
2024-05-24 15:12:45     self.gen.throw(typ, value, traceback)
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/callbacks/base.py", line 190, in event
2024-05-24 15:12:45     event.on_end(payload=payload)
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/callbacks/base.py", line 286, in on_end
2024-05-24 15:12:45     self._callback_manager.on_event_end(
2024-05-24 15:12:45   File "/usr/local/lib/python3.11/site-packages/llama_index/core/callbacks/base.py", line 131, in on_event_end
2024-05-24 15:12:45     handler.on_event_end(event_type, payload, event_id=event_id, **kwargs)
2024-05-24 15:12:45   File "/app/create_llama/backend/app/api/routers/messaging.py", line 123, in on_event_end
2024-05-24 15:12:45     if event.to_response() is not None:
2024-05-24 15:12:45        ^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/app/create_llama/backend/app/api/routers/messaging.py", line 81, in to_response
2024-05-24 15:12:45     return self.get_agent_tool_response()
2024-05-24 15:12:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-24 15:12:45   File "/app/create_llama/backend/app/api/routers/messaging.py", line 48, in get_agent_tool_response
2024-05-24 15:12:45     response = self.payload.get("response")
2024-05-24 15:12:45                ^^^^^^^^^^^^^^^^
2024-05-24 15:12:45 AttributeError: 'NoneType' object has no attribute 'get'

**Comment by l33tm3** [comment]
New: 2024-05-24 15:33:55 /usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_provider" has conflict with protected namespace "model_".
2024-05-24 15:33:55 
2024-05-24 15:33:55 You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ('settings_',)`.
2024-05-24 15:33:55   warnings.warn(

**Comment by l33tm3** [comment]
![image](https://github.com/ragapp/ragapp/assets/94154870/e55f914e-31e1-4893-820f-c101f2fce6a5)
i will change and send PR

**Comment by l33tm3** [comment]
PR accepted ! Close this treath
