### ISSUE TITLE
docker build issue

### ISSUE THREAD

**Issue by nilaan-effectz** [ragapp/ragapp#120]
**Describe the bug**
I cloned the repo and build docker image and getting error while building nextjs application

**To Reproduce**
1. clone repo : `git clone https://github.com/ragapp/ragapp.git`
2. build docker image `docker build -t local/ragapp .`

**Expected behavior**
build docker image succesfully

**Desktop (please complete the following information):**
 - OS: Windows 11/linux ( faced this issue in both env)
 - Browser chrome

**Additional context Error log**
87.08 > create_llama@0.1.0 build /app/create_llama/frontend
87.08 > next build
87.08
88.12 Attention: Next.js now collects completely anonymous telemetry regarding usage.
88.12 This information is used to shape Next.js' roadmap and prioritize features.
88.12 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
88.12 https://nextjs.org/telemetry
88.12
88.21   ▲ Next.js 14.2.5
88.21
88.32    Creating an optimized production build ...
129.1  ✓ Compiled successfully
129.1    Linting and checking validity of types ...
143.0    Collecting page data ...
146.1    Generating static pages (0/6) ...
146.9    Generating static pages (1/6)
146.9    Generating static pages (2/6)
147.1    Generating static pages (4/6)
147.4 TypeError: Promise.withResolvers is not a function
147.4     at 47060 (/app/create_llama/frontend/.next/server/chunks/444.js:115:60043)
147.4     at t (/app/create_llama/frontend/.next/server/webpack-runtime.js:1:127)
147.4     at 81407 (/app/create_llama/frontend/.next/server/chunks/242.js:1:12394)
147.4     at Object.t [as require] (/app/create_llama/frontend/.next/server/webpack-runtime.js:1:127)
147.4     at require (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18490)
147.4     at I (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94362)
147.4     at C (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:92913)
147.4     at rP (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33974)
147.4     at nN (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:62304)
147.4     at nB (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538) {
147.4   digest: '2205930751'
147.4 }
147.4
147.4 Error occurred prerendering page "/chat". Read more: https://nextjs.org/docs/messages/prerender-error
147.4
147.4 TypeError: Promise.withResolvers is not a function
147.4     at 47060 (/app/create_llama/frontend/.next/server/chunks/444.js:115:60043)
147.4     at t (/app/create_llama/frontend/.next/server/webpack-runtime.js:1:127)
147.4     at 81407 (/app/create_llama/frontend/.next/server/chunks/242.js:1:12394)
147.4     at Object.t [as require] (/app/create_llama/frontend/.next/server/webpack-runtime.js:1:127)
147.4     at require (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18490)
147.4     at I (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94362)
147.4     at C (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:92913)
147.4     at rP (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33974)
147.4     at nN (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:62304)
147.4     at nB (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
147.4 TypeError: Promise.withResolvers is not a function
147.4     at 47060 (/app/create_llama/frontend/.next/server/chunks/444.js:115:60043)
147.4     at t (/app/create_llama/frontend/.next/server/webpack-runtime.js:1:127)
147.4     at 81407 (/app/create_llama/frontend/.next/server/chunks/242.js:1:12394)
147.4     at Object.t [as require] (/app/create_llama/frontend/.next/server/webpack-runtime.js:1:127)
147.4     at require (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18490)
147.4     at I (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94362)
147.4     at C (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:92913)
147.4     at rP (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33974)
147.4     at nN (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:62304)
147.4     at nB (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538) {
147.4   digest: '2205930751'
147.4 }
147.5
147.5 Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
147.5
147.5 TypeError: Promise.withResolvers is not a function
147.5     at 47060 (/app/create_llama/frontend/.next/server/chunks/444.js:115:60043)
147.5     at t (/app/create_llama/frontend/.next/server/webpack-runtime.js:1:127)
147.5     at 81407 (/app/create_llama/frontend/.next/server/chunks/242.js:1:12394)
147.5     at Object.t [as require] (/app/create_llama/frontend/.next/server/webpack-runtime.js:1:127)
147.5     at require (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18490)
147.5     at I (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94362)
147.5     at C (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:92913)
147.5     at rP (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33974)
147.5     at nN (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:62304)
147.5     at nB (/app/create_llama/frontend/node_modules/.pnpm/next@14.2.5_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
147.5  ✓ Generating static pages (6/6)
147.5
147.5 > Export encountered errors on following paths:
147.5   /chat/page: /chat
147.5   /page: /
147.6  ELIFECYCLE  Command failed with exit code 1.
147.6 make: *** [Makefile:33: build-chat] Error 1
------

 1 warning found (use --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
Dockerfile:18
--------------------
  16 |
  17 |     # Build static files for the Chat UI
  18 | >>> RUN make build-frontends
  19 |
  20 |     # ======= RELEASE ==========
--------------------
ERROR: failed to solve: process "/bin/sh -c make build-frontends" did not complete successfully: exit code: 2

**Comment by marcusschiesser** [comment]
@nilaan-effectz please try again with the latest `main`, Docker build works, see https://github.com/ragapp/ragapp/actions/runs/10141484777
