### ISSUE TITLE
Failed to upload pdf file

### ISSUE THREAD

**Issue by ydniuyongjie** [ragapp/ragapp#135]
When I upload a pdf file, it always prompts a failure, I don't know what it is.

![失败](https://github.com/user-attachments/assets/601c4e5e-4cf7-428e-b8f6-244520f4a9f0)

**Comment by marcusschiesser** [comment]
please add the log output and ideally add the PDF file for testing

**Comment by YinJiangyi** [comment]
also occured this error.

AttributeError: 'str' object has no attribute 'data'
INFO:root:Generate index for the provided data
INFO:app.engine.loaders:Loading documents from loader: file, config: {'use_llama_parse': False}
WARNING:app.engine.loaders.file:Failed to load file documents, error message: No files found in data. . Return as empty document list.
Parsing nodes: 0it [00:00, ?it/s]
Generating embeddings: 0it [00:00, ?it/s]
INFO:root:Finished generating the indexs]
INFO:     192.168.107.219:54685 - "DELETE /api/management/files/docs-mesalab-iie-cn-pages-viewpage-action-pageid-96722028.pdf HTTP/1.1" 200 OK
INFO:     192.168.107.219:64638 - "PUT /api/management/reranker HTTP/1.1" 200 OK
INFO:     192.168.107.219:64638 - "GET /api/management/reranker HTTP/1.1" 200 OK
INFO:     192.168.107.219:64638 - "PUT /api/management/reranker HTTP/1.1" 200 OK
INFO:     192.168.107.219:64638 - "GET /api/management/reranker HTTP/1.1" 200 OK
INFO:     192.168.107.219:64638 - "POST /api/management/loader HTTP/1.1" 200 OK
INFO:     192.168.107.219:64638 - "GET /api/management/loader?loader_name=file HTTP/1.1" 200 OK
INFO:     192.168.107.219:64638 - "POST /api/management/loader HTTP/1.1" 200 OK
INFO:     192.168.107.219:64638 - "GET /api/management/loader?loader_name=file HTTP/1.1" 200 OK
INFO:     192.168.107.219:64638 - "POST /api/management/loader HTTP/1.1" 200 OK
INFO:     192.168.107.219:64638 - "GET /api/management/loader?loader_name=file HTTP/1.1" 200 OK
INFO:     192.168.107.219:64638 - "POST /api/management/loader HTTP/1.1" 200 OK
INFO:     192.168.107.219:64638 - "GET /api/management/loader?loader_name=file HTTP/1.1" 200 OK
INFO:     192.168.107.219:64640 - "GET /api/management/agents HTTP/1.1" 200 OK
INFO:root:Generate index for the provided data
INFO:app.engine.loaders:Loading documents from loader: file, config: {'use_llama_parse': False}
Generating embeddings:  75%|███████▌  | 3/4 [00:45<00:15, 15.06s/it]
Parsing nodes: 100%|██████████| 2/2 [00:00<00:00, 431.62it/s]
Generating embeddings:   0%|          | 0/4 [00:00<?, ?it/s]INFO:httpx:HTTP Request: POST https://api.xhub.chat/embeddings "HTTP/1.1 200 OK"
INFO:     192.168.107.219:64640 - "POST /api/management/files HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/routers/management/files.py", line 23, in add_file
    res = await FileHandler.upload_file(file, str(file.filename), fileIndex, totalFiles)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/controllers/files.py", line 51, in upload_file
    index_all()
  File "/app/backend/tasks/indexing.py", line 12, in index_all
    generate_datasource()
  File "/app/create_llama/backend/app/engine/generate.py", line 75, in generate_datasource
    _ = run_pipeline(docstore, vector_store, documents)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/create_llama/backend/app/engine/generate.py", line 49, in run_pipeline
    nodes = pipeline.run(show_progress=True, documents=documents)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 543, in run
    nodes = run_transformations(
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 97, in run_transformations
    nodes = transform(nodes, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/base/embeddings/base.py", line 443, in __call__
    embeddings = self.get_text_embedding_batch(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/base/embeddings/base.py", line 335, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/embeddings/openai/base.py", line 432, in _get_text_embeddings
    return get_embeddings(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/embeddings/openai/base.py", line 180, in get_embeddings
    data = client.embeddings.create(input=list_of_text, model=engine, **kwargs).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/resources/embeddings.py", line 124, in create
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 954, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1060, in _request
    return self._process_response(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1159, in _process_response
    return api_response.parse()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_response.py", line 319, in parse
    parsed = self._options.post_parser(parsed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/resources/embeddings.py", line 112, in parser
    for embedding in obj.data:
                     ^^^^^^^^
AttributeError: 'str' object has no attribute 'data'
INFO:root:Generate index for the provided data
INFO:app.engine.loaders:Loading documents from loader: file, config: {'use_llama_parse': False}
WARNING:app.engine.loaders.file:Failed to load file documents, error message: No files found in data. . Return as empty document list.
Parsing nodes: 0it [00:00, ?it/s]
Generating embeddings: 0it [00:00, ?it/s]
INFO:root:Finished generating the indexs]
INFO:     192.168.107.219:64656 - "DELETE /api/management/files/96722028.pdf HTTP/1.1" 200 OK

**Comment by rehan243** [comment]
Looks like this might be an issue with file size or MIME type validation on upload. I've hit something similar before where the backend rejects certain PDFs due to missing headers.

Check if your backend is expecting a `Content-Type: application/pdf` header during the upload. Here's a quick example for how I've handled this in Flask:

```python
if file.mimetype != 'application/pdf':
    return {"error": "Invalid file type"}, 400
```

Are you running this locally or deploying somewhere like AWS? Curious if this happens with *every* PDF or just certain ones.
