### ISSUE TITLE
Error - not able to run ragapp successfully

### ISSUE THREAD

**Issue by pixelpunch** [ragapp/ragapp#22]
I am on MacOS Monterey 12.7.4
Python v3.8.2
Docker v20.10.2

I have pulled the image from Docker Hub and then ran the run command, but then I get this error -

```
✝  ~/llama  docker pull ragapp/ragapp
Using default tag: latest
latest: Pulling from ragapp/ragapp
Digest: sha256:f70bc1a0dba52e7b9668ab1fa4e1171ae1a6ae9df6ecb559f5037a84463c04af
Status: Image is up to date for ragapp/ragapp:latest
docker.io/ragapp/ragapp:latest
 ✝  ~/llama  docker run -p 8000:8000 ragapp/ragapp
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    from create_llama.backend.app.settings import init_settings
  File "/app/create_llama/backend/app/settings.py", line 3, in <module>
    from llama_index.core.settings import Settings
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/__init__.py", line 10, in <module>
    from llama_index.core.base.response.schema import Response
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/base/response/schema.py", line 9, in <module>
    from llama_index.core.schema import NodeWithScore
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/schema.py", line 15, in <module>
    from llama_index.core.utils import SAMPLE_TEXT, truncate_text
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/utils.py", line 89, in <module>
    globals_helper = GlobalsHelper()
                     ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/utils.py", line 45, in __init__
    import nltk
  File "/usr/local/lib/python3.11/site-packages/nltk/__init__.py", line 133, in <module>
    from nltk.collocations import *
  File "/usr/local/lib/python3.11/site-packages/nltk/collocations.py", line 36, in <module>
    from nltk.metrics import (
  File "/usr/local/lib/python3.11/site-packages/nltk/metrics/__init__.py", line 17, in <module>
    from nltk.metrics.aline import align
  File "/usr/local/lib/python3.11/site-packages/nltk/metrics/aline.py", line 41, in <module>
    import numpy as np
  File "/usr/local/lib/python3.11/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/usr/local/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/usr/local/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
  File "<frozen importlib._bootstrap>", line 216, in _lock_unlock_module
KeyboardInterrupt
```

**Comment by marcusschiesser** [comment]
@pixelpunch here people have similar issues with docker: https://github.com/HumanSignal/label-studio/issues/3070 - can you please try the workarounds described there and post your findings here

**Comment by pixelpunch** [comment]
@marcusschiesser this issue was resolved by updating Docker engine to 26.1.1

**Comment by fgonzalezlez** [comment]
If I already have an application installed on the 8000, how do I do it on another port?

**Comment by marcusschiesser** [comment]
@fgonzalezlez you can change the port using the -p parameter, see https://docs.docker.com/network/#published-ports
