### ISSUE TITLE
Could not fetch Ollama models. Make sure the Ollama base URL is accessible with RAGapp.

### ISSUE THREAD

**Issue by richardstevenhack** [ragapp/ragapp#78]
**Describe the bug**

On fresh install, got this message:
Could not fetch Ollama models. Make sure the Ollama base URL is accessible with RAGapp.
Also popup says "Failed to fetch Ollama models"

**To Reproduce**

1) docker run -p 8000:8000 ragapp/ragapp
2) Access the Admin UI at http://localhost:8000/admin to configure RAGapp.
3) Select Ollama as the Model Provider.
4) Check that Ollama is running: http://127.0.0.1:11434/ shows "Ollama is running."
3) Set Ollama URL to: http://172.17.0.1:11434 (Note: On Linux, http://host.docker.internal:11434 does not work.)
4) Tried http://localhost:11434 - also did not work.
5) tried http://0.0.0.1:11434 - this one just showed spinner never stopped.

**Expected behavior**

Expected a connection to Ollama and a list of available Ollama models to be displayed.

**Screenshots**

![Screenshot_20240627_010633](https://github.com/ragapp/ragapp/assets/44449170/0d8a6fd8-10a6-4387-abbc-2635972acf9f)

![Screenshot_20240627_010840](https://github.com/ragapp/ragapp/assets/44449170/34fbe93e-5eda-442b-a94d-bb50fcf65b94)

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed Linux
 - Browser: Firefox
 - Version: 127.0

**Smartphone (please complete the following information):**
N/A

**Additional context**

Nothing to add except that every one of several other GUI front ends to Ollama I have gotten working with either Docker or AppImages or Flatpaks. A couple did not work due to issues with their implementation.

**Comment by richardstevenhack** [comment]
I read the linked piece. It basically says use any random IP. I used http://172.17.0.1 because that's what worked with AnythingLLM and that is what they recommend:

https://docs.useanything.com/installation/self-hosted/local-docker

`Cannot connect to service running on localhost!
If you are in docker and cannot connect to a service running on your host machine running on a local interface or loopback:
    localhost
    127.0.0.1
    0.0.0.0
Important
On linux http://host.docker.internal:xxxx does not work. Use http://172.17.0.1:xxxx instead to emulate this functionality.
`
So what do I use to connect? Every other Docker front end I use uses http://172.17.0.1 successfully.

**Comment by richardstevenhack** [comment]
Here is an attempt to use the requested IP: http://host.docker.internal:11434

![Screenshot_20240627_035621](https://github.com/ragapp/ragapp/assets/44449170/90bdcf47-edf9-4faf-b510-9eb8d46911d9)


Didn't work. So what does in Docker on Linux?

**Comment by marcusschiesser** [comment]
Ah, now I got your problem. Sorry for the confusion. So the issue is that `http://172.17.0.1:11434` is not working. We'll need to test the networking of the containers.

On my Mac the following works:
```bash
# docker run -it ragapp/ragapp bash
root@431f021b67e8:/app# curl -v http://host.docker.internal:11434
*   Trying 192.168.65.254:11434...
* Connected to host.docker.internal (192.168.65.254) port 11434 (#0)
> GET / HTTP/1.1
> Host: host.docker.internal:11434
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 27 Jun 2024 12:05:20 GMT
< Content-Length: 17
<
* Connection #0 to host host.docker.internal left intact
Ollama is running
```

can you try:
```bash
# docker run -it ragapp/ragapp bash
root@ecaf3d0b4104:/app# curl -v http://172.17.0.1:11434
```

on your Linux machine? 

Anyone else having the same issue using Linux?

**Comment by richardstevenhack** [comment]
I got:
`rhack@localhost:/Data2/Work> docker run -it ragapp/ragapp bash
root@263c41b8aba9:/app# curl -v http://host.docker.internal:11434
* Could not resolve host: host.docker.internal
* Closing connection 0
curl: (6) Could not resolve host: host.docker.internal
root@263c41b8aba9:/app# curl -v http://172.17.0.1:11434
*   Trying 172.17.0.1:11434...
* connect to 172.17.0.1 port 11434 failed: Connection refused
* Failed to connect to 172.17.0.1 port 11434 after 0 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to 172.17.0.1 port 11434 after 0 ms: Couldn't connect to server
root@263c41b8aba9:/app# 
`

**Comment by richardstevenhack** [comment]
The curl has no problem connecting to ollama from the command line outside the Docker container:
`rhack@localhost:/Data2/Work> curl -v http://127.0.0.1:11434
*   Trying 127.0.0.1:11434...
* Connected to 127.0.0.1 (127.0.0.1) port 11434
> GET / HTTP/1.1
> Host: 127.0.0.1:11434
> User-Agent: curl/8.8.0
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 27 Jun 2024 12:40:55 GMT
< Content-Length: 17
< 
* Connection #0 to host 127.0.0.1 left intact
Ollama is running`

**Comment by richardstevenhack** [comment]
A lot of python tracebacks are generated while the app is sitting there doing its 120 second time out thing trying to get the models list. This is a portion of what that looks like, if it's any help:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/routers/management/config.py", line 92, in get_available_models
    return AIProvider.fetch_available_models(provider, provider_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/controllers/providers.py", line 31, in fetch_available_models
    return cls.fetch_ollama_models(provider_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/controllers/providers.py", line 14, in fetch_ollama_models
    res = client.list()
          ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ollama/_client.py", line 333, in list
    return self._request('GET', '/api/tags').json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ollama/_client.py", line 69, in _request
    response = self._client.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused
INFO:     172.17.0.1:57164 - "GET /api/management/config/models/list?provider=ollama&provider_url=http%3A%2F%2Flocalhost%3A11434 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/routers/management/config.py", line 92, in get_available_models
    return AIProvider.fetch_available_models(provider, provider_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/controllers/providers.py", line 31, in fetch_available_models
    return cls.fetch_ollama_models(provider_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/controllers/providers.py", line 14, in fetch_ollama_models
    res = client.list()
          ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ollama/_client.py", line 333, in list
    return self._request('GET', '/api/tags').json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ollama/_client.py", line 69, in _request
    response = self._client.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1]
rhack@localhost:/`

This looks like the relevant section:

`httpx.ConnectError: [Errno 111] Connection refused
INFO:     172.17.0.1:57164 - "GET /api/management/config/models/list?provider=ollama&provider_url=http%3A%2F%2Flocalhost%3A11434 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application`

**Comment by marcusschiesser** [comment]
Seems like a Docker network issue. Can you try it with the ubuntu image:

```
# docker run -it ubuntu:latest bash
root@a1ff946fd0a2:/# apt-get update && apt-get install -y curl
root@a1ff946fd0a2:/# curl -v http://172.17.0.1:11434
```

**Comment by richardstevenhack** [comment]
Didn't work:

`root@a48ff3649547:/# curl -v http://172.17.0.1:11434
*   Trying 172.17.0.1:11434...
* connect to 172.17.0.1 port 11434 from 172.17.0.2 port 35070 failed: Connection refused
* Failed to connect to 172.17.0.1 port 11434 after 0 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to 172.17.0.1 port 11434 after 0 ms: Couldn't connect to server
root@a48ff3649547:/# ^C
root@a48ff3649547:/#
root@a48ff3649547:/# curl -v http://127.0.0.1:11434
*   Trying 127.0.0.1:11434...
* connect to 127.0.0.1 port 11434 from 127.0.0.1 port 37116 failed: Connection refused
* Failed to connect to 127.0.0.1 port 11434 after 0 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to 127.0.0.1 port 11434 after 0 ms: Couldn't connect to server
root@a48ff3649547:/# curl -v http://localhost:11434
* Host localhost:11434 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:11434...
* connect to ::1 port 11434 from ::1 port 55728 failed: Connection refused
*   Trying 127.0.0.1:11434...
* connect to 127.0.0.1 port 11434 from 127.0.0.1 port 56948 failed: Connection refused
* Failed to connect to localhost port 11434 after 0 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to localhost port 11434 after 0 ms: Couldn't connect to server
root@a48ff3649547:/# `

**Comment by richardstevenhack** [comment]
Here's a comparison: I run Lobe Chat as one of the GUIs I'm testing. 
Here is the Docker command I use to run it:
docker run -d -p 3210:3210 -e OLLAMA_PROXY_URL=http://172.17.0.1:11434/v1 lobehub/lobe-chat

I open the browser and connect to: http://localhost:3210. No problem, Lobe Chat opens.

I go to Lobe Chat settings, select Ollama as the provider, and enter the URL as: https://127.0.0.1:11434

This was working before. I could go to the Just Chat, select Qwen2 and connect.

Today it doesn't work. So something has gone wrong with Docker, I assume. I'm going to try to rebuild the Lobe Chat image from scratch and see if I can figure out what's going on with that. Might help in figuring out Ragapp.

**Comment by richardstevenhack** [comment]
Doing some research on Google, it appears almost no one can get Docker to connect to Ollama. Do a search for "docker can not connect to Ollama" and look at the number of returns.

Clearly this is a mess. This is why I hate using Docker - it's a complicated mess if you want to connect to anything outside of it. A Flatpak or an AppImage is better.

Based on an article on the Open-WebUI Github, they suggest:

`If you're experiencing connection issues, it’s often due to the WebUI docker container not being able to reach the Ollama server at 127.0.0.1:11434 (host.docker.internal:11434) inside the container . Use the --network=host flag in your docker command to resolve this. Note that the port changes from 3000 to 8080, resulting in the link: http://localhost:8080.

Example Docker Command:

docker run -d --network=host -v open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://127.0.0.1:11434 --name open-webui --restart always ghcr.io/open-webui/open-webui:main

`
I tried that - using the "--network=host" and the "OLLAMA_BASE_URL" part - didn't work with Lobe Chat.

**Comment by richardstevenhack** [comment]
Holy shit, I got it working!  This is what I did:

1) Based on the Open WEBUI idea above, I ran this command:
 docker run --network=host -p 8000:8000 -e OLLAMA_BASE_URL=http://127.0.0.1:11434 ragapp/ragapp
This sets the Docker network to the host network and the URL to Ollama to the host URL and the Ollama port.

2) I opened the admin panel, selected Ollama, and changed the URL to http://127.0.0.1:11434 instead of host.docker.internal.

3) Selected the model qwen2:latest and hit update, it went to the chat page.

4) And it works. Initially the first time I did this it asked for the nomic embedding model to be pulled from Ollama, so I did that, and that prompt did not appear this second time.

**Comment by richardstevenhack** [comment]
That also worked for Lobe Chat!

I don't know if connecting the Docker network to the host network is a security risk, but since I'm running on my own machine with the usual firewalls, I don't really care as long as this works. Also I'm running on openSUSE Tumbleweed Linux, so Windows or another Linux your mileage may vary.

**Comment by marcusschiesser** [comment]
Does it also work if you set in the 1. step just:
```
docker run --network=host -p 8000:8000 ragapp/ragapp
```
(because the 2. step will set the OLLAMA_BASE_URL) parameter

**Comment by richardstevenhack** [comment]
Yup, that works, too. Just tested it.

**Comment by marcusschiesser** [comment]
closing (referenced in README)

**Comment by hasanfarisi** [comment]
Hi, lately I got some issues when running RAGapp using Ollama model, here's you have to update base on @richardstevenhack comment:

1. Installing new model qwen2:latest
`ollama run qwen2:latest`
2. after finish, install two packages below:
`ollama pull nomic-embed-text`
`ollama pull jina/jina-embeddings-v2-base-de`
3. Running your RAGapp with type this on your terminal
`docker run --network=host -p 8000:8000 -e OLLAMA_BASE_URL=http://127.0.0.1:11434/ ragapp/ragapp`
4. Select Ollama model like image below
<img width="816" alt="Screenshot 2024-10-23 at 11 39 43 AM" src="https://github.com/user-attachments/assets/6370c0e5-4dd9-4db9-8815-6effaff81546">
5. Finish and enjoy!
