### ISSUE TITLE
can't get a response from the model

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [ragapp/ragapp#87]
Hi

no matter what model I choose, I get the following error. 
I can choose the model and embedding is done if I upload a file for RAG purpose, but can't get a response back.

Here is the cmd i use:

here is the log:
`sudo docker run --network=host -p 8000:8000 ragapp/ragapp
`

```


INFO:     127.0.0.1:50714 - "GET /api/chat/config HTTP/1.1" 200 OK
INFO:     127.0.0.1:50722 - "GET /api/chat/config HTTP/1.1" 200 OK
INFO:     Connecting vector store...
INFO:app.engine.vectordb:Using vector provider: chroma
INFO:     Finished load index from vector store.
INFO:     127.0.0.1:59916 - "POST /api/chat HTTP/1.1" 200 OK
INFO:llama_index.core.chat_engine.condense_plus_context:Condensed question: tell me about yourself?
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434//api/chat "HTTP/1.1 301 Moved Permanently"
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-48' coro=<Dispatcher.span.<locals>.async_wrapper() done, defined at /usr/local/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py:212> exception=HTTPStatusError("Redirect response '301 Moved Permanently' for url 'http://127.0.0.1:11434//api/chat'\nRedirect location: '/api/chat'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 223, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/chat_engine/types.py", line 214, in awrite_response_to_history
    async for chat in self.achat_stream:
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 87, in wrapped_gen
    async for x in f_return_val:
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/llms/custom.py", line 58, in gen
    for message in self.stream_chat(messages, **kwargs):
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 170, in wrapped_gen
    for x in f_return_val:
  File "/usr/local/lib/python3.11/site-packages/llama_index/llms/ollama/base.py", line 178, in stream_chat
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Redirect response '301 Moved Permanently' for url 'http://127.0.0.1:11434//api/chat'
Redirect location: '/api/chat'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 265, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 238, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 587, in receive
    await self.message_event.wait()
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fd356e0f150

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
  |     await route.handle(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 258, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    |     await func()
    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/app/create_llama/backend/app/api/routers/chat.py", line 72, in content_generator
    |     async for output in streamer:
    |   File "/usr/local/lib/python3.11/site-packages/aiostream/aiter_utils.py", line 198, in __aexit__
    |     await self._aiterator.athrow(typ, value, traceback)
    |   File "/usr/local/lib/python3.11/site-packages/aiostream/stream/create.py", line 52, in from_iterable
    |     yield item
    |   File "/usr/local/lib/python3.11/site-packages/aiostream/stream/advanced.py", line 74, in base_combine
    |     result = task.result()
    |              ^^^^^^^^^^^^^
    |   File "/app/create_llama/backend/app/api/routers/chat.py", line 44, in _chat_response_generator
    |     async for token in response.async_response_gen():
    |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/chat_engine/types.py", line 272, in async_response_gen
    |     raise self.exception
    |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 223, in async_wrapper
    |     result = await func(*args, **kwargs)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/chat_engine/types.py", line 214, in awrite_response_to_history
    |     async for chat in self.achat_stream:
    |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 87, in wrapped_gen
    |     async for x in f_return_val:
    |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/llms/custom.py", line 58, in gen
    |     for message in self.stream_chat(messages, **kwargs):
    |   File "/usr/local/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 170, in wrapped_gen
    |     for x in f_return_val:
    |   File "/usr/local/lib/python3.11/site-packages/llama_index/llms/ollama/base.py", line 178, in stream_chat
    |     response.raise_for_status()
    |   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    |     raise HTTPStatusError(message, request=request, response=self)
    | httpx.HTTPStatusError: Redirect response '301 Moved Permanently' for url 'http://127.0.0.1:11434//api/chat'
    | Redirect location: '/api/chat'
    | For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301
    +------------------------------------


```

Thanks in advance

**Comment by marcusschiesser** [comment]
@SuroshAhmadZobair how did you configure the Ollama URL? seems like you added a `/` too much
